# Generated by Django 6.0.2 on 2026-07-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contribution',
            new_name='Saving',
        ),
    ]
