# Generated by Django 6.0.2 on 2026-07-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0003_member_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_repayable',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
