# Generated by Django 6.1.1 on 2026-09-11 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0004_loan_total_interest_loan_total_repayable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='sacco.member'),
        ),
    ]
